### ISSUE TITLE
Update to latest Next.js

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-nextjs#555]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

all

### Plugin version

8.0.0

### Node.js version

all

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

Due to updates in Next.js, the tests are failing because `.inject()` is not compatible anymore with Next.js. They shipped this change in a semver-minor :(.

We need some help in updating this module.

### Steps to Reproduce

update Next.js and run the tests.

**Comment by mcollina** [comment]
@SimenB I think you are using this module, so maybe this is something you might want to take on.

**Comment by SimenB** [comment]
We use this yes, but we don't use `inject` with it (we don't test the server part of this, just client side 🙈). We've been using 12.1.x in production since march fwiw without issues, so the compatibility issue seems to be with `inject` (`light-my-request`?) and not a "real" request?

I unfortunately don't have the capacity at the moment to dig into this, sorry!

**Comment by mcollina** [comment]
The current state is that the tests for this module are not passing and fixing them is a blocker for updating to Fastify v4.

**Comment by SimenB** [comment]
would migrating to using real requests be an option (i.e. `.listen` and undici or something)?

**Comment by mcollina** [comment]
Migrating to real requests would be ok too.

**Comment by SimenB** [comment]
@mcollina FWIW, 12.0.9 (and 12.0.10) fails the tests, so it's not just 12.1 which fails. This repo has 12.0.8 in its lockfile, seems to be the last one that works. Migrating to real requests doesn't help much (`19 failed, 26 passed, of 45` vs `23 failed, 15 passed, of 38` on master (no idea how `tap` counts, so might be worse for all I know)).

Since I spent the time on migrating, I've pushed up the code (https://github.com/fastify/fastify-nextjs/tree/real-requests), but since it doesn't fix the issue that doesn't help much

**Comment by mcollina** [comment]
Ouch, it seems worse than expected. I'm a bit concerned in the long-term feasibility of this module.

**Comment by mcollina** [comment]
@kurtextrem as you are using in prod, you might want to check this!

**Comment by stefee** [comment]
We're using this in prod currently. I can work on a re-write privately and publish when I'm done. It might make more sense to maintain outside of the `@fastify` scope as a private project.

I would note also that the Next.js team seems to prefer people not to use this approach at all. https://github.com/vercel/next.js/pull/35618#pullrequestreview-1019409127

**Comment by galvez** [comment]
FYI Most common Next.js features are supported by [Fastify DX for React](https://github.com/fastify/fastify-dx).

**Comment by stefee** [comment]
We are using Next.js for many reasons such as popularity and React 18 features like Streaming SSR, but partly because of the `next export` feature for SSG which will reduce our server infrastructure costs a lot for internal-facing applications, which probably don't really need SSR. React SSR is quite expensive to run. https://nextjs.org/docs/advanced-features/static-html-export

**Comment by jessekrubin** [comment]
FWIW: This WAS an issue/bug for my team with next 12.2.0 but has not been for 12.2.1 and 12.2.2

**Comment by stefee** [comment]
I've just published an unofficial plugin called [fastify-next](https://www.npmjs.com/package/fastify-next) which has support for Fastify v4 and [some other changes](https://github.com/stefee/fastify-next#comparison-with-fastifynextjs).

Source code is here: https://github.com/stefee/fastify-next/blob/main/src/index.ts

This is not yet a stable release (v0.x) so I don't recommend using in production just yet.

**Comment by mcollina** [comment]
The problem that Next.js is fundamentally incompatible with one of the basic primitives of Fastify (inject) remains.

**Comment by stefee** [comment]
I recommend that people mock Next.js in tests.

**Comment by mcollina** [comment]
That would be a reasonable approach to upgrade this.

**Comment by drakhart** [comment]
Hi guys! I've opened and referenced a PR migrating all tests to real requests, as suggested and inspired by [SimenB](https://github.com/SimenB), and updating Next to the latest version, and everything seems to be working fine. Please have a look at it whenever you can. 🙏 

As a side note, mocking Next.js didn't sound really appealing to me, since we're testing the actual integration between Fastify and Next.js and mocking one of them could yield unreally optimistic results.
